from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAllBooks200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, author=None, id=None, title=None, year=None):  # noqa: E501
        """GetAllBooks200ResponseInner - a model defined in OpenAPI

        :param author: The author of this GetAllBooks200ResponseInner.  # noqa: E501
        :type author: str
        :param id: The id of this GetAllBooks200ResponseInner.  # noqa: E501
        :type id: float
        :param title: The title of this GetAllBooks200ResponseInner.  # noqa: E501
        :type title: str
        :param year: The year of this GetAllBooks200ResponseInner.  # noqa: E501
        :type year: float
        """
        self.openapi_types = {
            'author': str,
            'id': float,
            'title': str,
            'year': float
        }

        self.attribute_map = {
            'author': 'author',
            'id': 'id',
            'title': 'title',
            'year': 'year'
        }

        self._author = author
        self._id = id
        self._title = title
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllBooks200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Get_all_books_200_response_inner of this GetAllBooks200ResponseInner.  # noqa: E501
        :rtype: GetAllBooks200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author(self) -> str:
        """Gets the author of this GetAllBooks200ResponseInner.


        :return: The author of this GetAllBooks200ResponseInner.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this GetAllBooks200ResponseInner.


        :param author: The author of this GetAllBooks200ResponseInner.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def id(self) -> float:
        """Gets the id of this GetAllBooks200ResponseInner.


        :return: The id of this GetAllBooks200ResponseInner.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this GetAllBooks200ResponseInner.


        :param id: The id of this GetAllBooks200ResponseInner.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this GetAllBooks200ResponseInner.


        :return: The title of this GetAllBooks200ResponseInner.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this GetAllBooks200ResponseInner.


        :param title: The title of this GetAllBooks200ResponseInner.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def year(self) -> float:
        """Gets the year of this GetAllBooks200ResponseInner.


        :return: The year of this GetAllBooks200ResponseInner.
        :rtype: float
        """
        return self._year

    @year.setter
    def year(self, year: float):
        """Sets the year of this GetAllBooks200ResponseInner.


        :param year: The year of this GetAllBooks200ResponseInner.
        :type year: float
        """
        if year is None:
            raise ValueError("Invalid value for `year`, must not be `None`")  # noqa: E501

        self._year = year
